baseURL = "/"
languageCode = "en-us"
title = "dreamers.cash"

author = "bt3"
copyright = "ğŸª 2077 cyberfuture metaverse by bt3"
paginate = 15
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

theme = "origin"

[params]
  favicon = "img/favicon.ico"
  featured = true
  cssonly = false

  [params.socials]
    facebook = ""
    twitter = ""
    instagram = ""
    youtube = ""
    github = ""
    gitlab = ""
    linkedin = ""
    slack = ""
    stackoverflow = ""
    medium= ""

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.highlight]
    style = "github"
    tabWidth = 4

[markup.goldmark.renderer]
unsafe = true

