baseURL = "/"
languageCode = "en-us"
title = "dreamers.cash"

author = "bt3"
copyright = "first they ignore us, then they laugh at us, then they fight us, then we win ü™ê cyberfuture 2021 "
paginate = 4
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

theme = "origin"

[params]
  favicon = "img/favicon.ico"
  description = "all that inexorable cypherpunk stuff..."
  featured = true
  cssonly = false

  [params.socials]
    facebook = ""
    twitter = ""
    instagram = ""
    youtube = ""
    github = ""
    gitlab = ""
    linkedin = ""
    slack = ""
    stackoverflow = ""
    medium= ""

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[markup]
  [markup.highlight]
    style = "github"
    tabWidth = 4

[markup.goldmark.renderer]
unsafe = true

